src/Entity/Donation.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DonationRepository")
 */
class Donation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $don_value;

    /**
     * @ORM\Column(type="datetime")
     */
    private $don_date;

    /**
     * @ORM\Column(type="text")
     */
    private $don_comm;



    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="donations")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Project", inversedBy="donations")
     */
    private $project;


    public function getId()
    {
        return $this->id;
    }

    public function getDonValue(): ?float
    {
        return $this->don_value;
    }

    public function setDonValue(float $don_value): self
    {
        $this->don_value = $don_value;

        return $this;
    }

    public function getDonDate(): ?\DateTimeInterface
    {
        return $this->don_date;
    }

    public function setDonDate(\DateTimeInterface $don_date): self
    {
        $this->don_date = $don_date;

        return $this;
    }

    public function getDonComm(): ?string
    {
        return $this->don_comm;
    }

    public function setDonComm(string $don_comm): self
    {
        $this->don_comm = $don_comm;

        return $this;
    }


    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(?Project $project): self
    {
        $this->project = $project;

        return $this;
    }

    public function __toString(){
        return 'Donation';
     }
}

templates/Profile/index.html.twig
{% extends 'baseform.html.twig' %}

{% block title %}Profile{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div id="profil">
            <div class="col-sm-4">
            </div>
                <div class="col-sm-12">
                    <ul class="nav nav-tabs mx-auto">
                        <li class="active"><a href="#info" data-toggle="tab">Profile</a></li>
                        <li><a href="#don" data-toggle="tab">History donation</a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active mx-auto" id="info">
                            <div class="col-sm-10">
                                <table id="tab" class="table table-bordered table-condensed table-hover table-striped">
                                    <thead>
                                    <tr>
                                        <th>Full name</th>
                                    </thead>
                                    <tbody>
                                        <td>{{ user.fullName }}</td>
                                    </tbody>
                                    </tr>
                                    <thead>
                                    <tr>
                                        <th>Username</th>
                                    </thead>
                                    <tbody>
                                    <td>{{ user.username }}</td>
                                    </tbody>
                                    </tr>
                                    <thead>
                                    <tr>
                                        <th>Email address</th>
                                    </thead>
                                    <tbody>
                                    <td>{{ user.email }}</td>
                                    </tbody>
                                    </tr>
                                </table>
                            </div>
                        </div>
                        <div class="tab-pane mx-auto" id="don">
                            <div class="col-sm-10">
                                <table id="tab" class="table table-bordered table-condensed table-hover table-striped">
                                    <thead>
                                    <tr>
                                        <th>Date</th>
                                        <th>Amount</th>
                                        <th>Project</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for don in donlist %}
                                    <tr>
                                        <td>{{ don.donDate|date('Y-m-d') }}</td>
                                        <td>{{ don.donValue }} $</td>
                                        <td>{{ don.Project }}</td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                    </div>
                </div>
    </div>
</div>


    
    
    

{% endblock %}