src/Entity/BlogComm.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BlogCommRepository")
 */
class BlogComm
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;




    /**
     * @ORM\Column(type="datetime")
     */
    private $post_date;

    /**
     * @ORM\Column(type="text")
     */
    private $post_content;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\BlogPost", inversedBy="blogComms")
     */
    private $Post;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="blogComms")
     */
    private $Author;

    public function getId()
    {
        return $this->id;
    }

    public function getPostId(): ?int
    {
        return $this->post_id_;
    }

    public function setPostId(int $post_id_): self
    {
        $this->post_id_ = $post_id_;

        return $this;
    }

    public function getPostDate(): ?\DateTimeInterface
    {
        return $this->post_date;
    }

    public function setPostDate(\DateTimeInterface $post_date): self
    {
        $this->post_date = $post_date;

        return $this;
    }

    public function getPostContent(): ?string
    {
        return $this->post_content;
    }

    public function setPostContent(string $post_content): self
    {
        $this->post_content = $post_content;

        return $this;
    }

    public function getPost(): ?BlogPost
    {
        return $this->Post;
    }

    public function setPost(?BlogPost $Post): self
    {
        $this->Post = $Post;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->Author;
    }

    public function setAuthor(?User $Author): self
    {
        $this->Author = $Author;

        return $this;
    }
    
    public function __toString(){
        // to show the name of the Category in the select
        return 'Comm';
   
    }
}

src/Entity/BlogPost.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BlogPostRepository")
 */
class BlogPost
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $post_title;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="text")
     */
    private $post_content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $post_tag;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="blogPosts")
     */
    private $Author;

    /**
     * @ORM\Column(type="string")
     */
    private $img;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\BlogComm", mappedBy="Post")
     */
    private $blogComms;

    public function __construct()
    {
        $this->blogComms = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getPostTitle(): ?string
    {
        return $this->post_title;
    }

    public function setPostTitle(string $post_title): self
    {
        $this->post_title = $post_title;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

  
    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getPostContent(): ?string
    {
        return $this->post_content;
    }

    public function setPostContent(string $post_content): self
    {
        $this->post_content = $post_content;

        return $this;
    }

    public function getPostTag(): ?string
    {
        return $this->post_tag;
    }

    public function setPostTag(string $post_tag): self
    {
        $this->post_tag = $post_tag;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->Author;
    }

    public function setAuthor(?User $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(string $img): self
    {
        $this->img = $img;

        return $this;
    }

    /**
     * @return Collection|BlogComm[]
     */
    public function getBlogComms(): Collection
    {
        return $this->blogComms;
    }

    public function addBlogComm(BlogComm $blogComm): self
    {
        if (!$this->blogComms->contains($blogComm)) {
            $this->blogComms[] = $blogComm;
            $blogComm->setPost($this);
        }

        return $this;
    }

    public function removeBlogComm(BlogComm $blogComm): self
    {
        if ($this->blogComms->contains($blogComm)) {
            $this->blogComms->removeElement($blogComm);
            // set the owning side to null (unless already changed)
            if ($blogComm->getPost() === $this) {
                $blogComm->setPost(null);
            }
        }

        return $this;
    }
   
    public function __toString(){
        // to show the name of the Category in the select
        return $this->post_title;
   
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use App\Entity\BlogPost;
use App\Entity\BlogComm;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\BlogPostRepository;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

/**
 * @Route("/blog")
*/
class BlogController extends Controller
{
    /**
     * @Route("/{page}", name="blog",requirements={"page"="\d+"})
     */
    public function index(BlogPostRepository $blogPostRepository,  $page = 0)
    {
    $rep = $this->getDoctrine()->getRepository(BlogPost::class);
    $posts = $rep->findAll();

    $postsPage = $blogPostRepository->findParPage($page, 3);

   



        return $this->render('Blog/index.html.twig' ,[
            'user' => $this->getUser(),
            'post' => $postsPage,
            'page' => $page
            
        ]);
    }

    /**
     * @Route("/search", name="search")
     */
    public function search(BlogPostRepository $blogPostRepository, Request $request)
    {
        if ($request->isMethod('POST')){
            $value = $request->request->get('value');
            $posts = $blogPostRepository->search($value);
            return $this->render('Blog/search.html.twig',['value' => $value, 'posts' =>$posts ]);
        }
       
        return $this->render('Blog/search.html.twig');
    }

    /**
     * @Route("/posts/{name}",name="post")
     */
    public function post($name, Request $request)
    {
        $req = $this->getDoctrine()->getRepository(BlogPost::class);
        $post = $req->findOneby(['id' => $name]);
        $user = $this->getUser();
        
        $comm = new BlogComm();
        $comm->setPostDate(new \Datetime('now'));
        $comm->setAuthor($user);
        $comm->setPost($post);
        
        $form = $this->createFormBuilder($comm)
        ->add('post_content', TextareaType::class)            
        ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
             // On enregistre l'utilisateur dans la base
            $em = $this->getDoctrine()->getManager();
            $em->persist($comm);
            $em->flush();
 

 
            return $this->redirectToRoute('post', ['name' => $name]);
        }

        //Il faut générer le formulaire pour les commentaires et les afficher
        return $this->render('Blog/post.html.twig',['post' => $post, 'form' => $form->createView(), 'user' => $this->getUser()]);
    }
}

templates/Blog/index.html.twig
{% extends 'baseblog.html.twig' %}

{% block title %}Blog - {{parent()}}{% endblock %}


{% block content %}
<div class="container post">



    {% for post in post %}
      {% if loop.first %}
<div class="row">
    <div class="card mb-4 col-md-12 mx-auto" id="art1">
      <a href="{{ path('post', { 'name': post.id }) }}"><img class="card-img-top" src="{{ post.img }}" alt="post img"></a>
        <div class="card-body">
        <h4 class="card-title">
          <a href="{{ path('post', { 'name': post.id }) }}">{{ post.postTitle }}</a>
          </h4>
               <a href="{{ path('post', { 'name': post.id }) }}" class="btn btn-primary">Read More &rarr;</a>
        </div>
                 <div class="card-footer text-muted">
                   Published on {{ post.Date|date('F, jS \\a\\t g:ia') }} by {{ post.Author }}.
                </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}


  <div class="row">
    {% set nb = 0 %}
    {% for post in post %}
    {% if not loop.first and nb < 2 %}
    {% set nb = nb +1 %}
    <div class="col-lg-6 mx-auto portfolio-item">
      <div class="card h-100">
        <a href="{{ path('post', { 'name': post.id }) }}"><img class="card-img-top" src="{{ post.img }}" alt=""></a>
        <div class="card-body">
          <h4 class="card-title">
            <a href="{{ path('post', { 'name': post.id }) }}">{{ post.postTitle }}</a>
          </h4>
          <a href="{{ path('post', { 'name': post.id }) }}" class="btn btn-primary">Read More &rarr;</a>
      <hr>
        <div class="card-footer text-muted">
          Published on {{ post.Date|date('F, jS \\a\\t g:ia') }} by {{ post.Author }}.
        </div>
        </div>
      </div>
    </div>
      {% endif %}
      {% endfor %}
    </div>
      <!-- /.row -->
      <div class="mx-auto text-center">
      {% if page < 3 %}
      <a href="{{ path('blog',{ 'page': page + 3 }) }}"> Next >> </p> 
      {% else %}
      <a href="{{ path('blog',{ 'page': page - 3 }) }}"> << Prev </p>
      {% endif %}
      </div>
    </div>
    

</div>
{% endblock %}

templates/Blog/post.html.twig
{% extends 'baseblog.html.twig' %}



{% block content %}
<!-- Page Content -->
    <div class="container post">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Titre -->
          <h1 class="mt-4">{{ post.postTitle }}</h1>

          <!-- Auteur -->
          <p class="lead">
            by
            <a href="#">{{ post.Author }}</a>
          </p>

          <hr>

          <!-- Date -->
          <p>Published on {{ post.Date|date('F, jS \\a\\t g:ia') }}</p>

          <hr>

          <!-- Preview Image -->
          <img class="img-fluid rounded" src="{{ post.img }}" alt="post image">

          <hr>

          <!-- Post Content -->
          <p class="lead">{{ post.postContent }}</p>

          <cite title="Source Title">Tags : {{ post.postTag }}</cite>

          <hr>

        <!-- Single Comment -->
          <div class="media mb-4">
          <div class="media-body">
            {% if post.blogComms is empty %}
            <p>No comments for the moment. Be the first One !</p>
            {% else %}
            <div class="text-center">
            <h5>Comments section</h5>
            </div>
            {% for comm in post.blogComms %}
            <hr>
            <h6 class="mt-0">{{ comm.Author }} - {{ comm.postDate|date('F jS, g:ia') }}</h6>
            <p>{{ comm.postContent }}</p>
            {% endfor %}
            {% endif %}
              
            </div>
          </div>

        
          <!-- Comments Form -->
          {% if user.username is defined %}
          <div class="card my-4">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body">
              {{ form_start(form) }}
                <div class="form-group">
                  {{ form_row(form.post_content, {'attr': {'class': 'form-control','placeholder':'Your comment here...','rows':'5'}}) }}
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
              {{ form_end(form) }}
            </div>
          </div>
          {% else %}
          <div class="card my-4">
            <h5 class="card-header">You must be logged in to comment ! <a href="{{path('security_login')}}">Log in</a>.</h5>
          </div>
          {% endif %}
        </div>
        </div>
        </div>
        {% endblock %}

templates/Blog/search.html.twig
{% extends 'baseform.html.twig' %}


{% block content %}

<div class="search text-white text-center">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
            </div>
            <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
                <form action="{{path('search')}}" method="POST">
                    <div class="form-row barre">
                        <div class="col-12 col-md-9 mb-2 mb-md-0">
                            <input type="text" name="value" class="form-control form-control-lg" placeholder="Search per tag...">
                        </div>
                        <div class="col-12 col-md-3">
                            <button type="submit" class="btn btn-block btn-lg btn-primary">Search</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    {% if posts is defined %}
    <p>Search results for :{{ value }}</p>

    {% for post in posts %}
    <div class="row">
       <div class="card mb-4 col-md-12 mx-auto" id="art1">
        <a href="{{ path('post', { 'name': post.id }) }}"><img class="card-img-top" src="{{ post.img }}" alt="post img"></a>
            <div class="card-body">
            <h4 class="card-title">
            <a href="{{ path('post', { 'name': post.id }) }}">{{ post.postTitle }}</a>
            </h4>
               <a href="{{ path('post', { 'name': post.id }) }}" class="btn btn-primary">Read More &rarr;</a>
            </div>
            <div class="card-footer text-muted">
            Published on {{ post.Date|date('F, jS \\a\\t g:ia') }} by {{ post.Author }}.
            </div>
        </div>
    </div>
{% endfor %}
{% endif %}
    </div>

{% endblock %}